// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6NwARZV1DRw9uMqNaYgxx_5BTcPsjbU',
    appId: '1:963645798761:web:f7fcd7b692d2e6063e25f8',
    messagingSenderId: '963645798761',
    projectId: 'cooperadora-app',
    authDomain: 'cooperadora-app.firebaseapp.com',
    storageBucket: 'cooperadora-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKUJQmEDRwhV1vUVCeA4PmyWMrdKxSAk',
    appId: '1:963645798761:android:615eae72a30ba7653e25f8',
    messagingSenderId: '963645798761',
    projectId: 'cooperadora-app',
    storageBucket: 'cooperadora-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr65m_sh_sn_EnTyer4TvFNcqmEsfyeqI',
    appId: '1:963645798761:ios:50d081e853bbfa773e25f8',
    messagingSenderId: '963645798761',
    projectId: 'cooperadora-app',
    storageBucket: 'cooperadora-app.firebasestorage.app',
    iosBundleId: 'com.example.cooperadoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl6NwARZV1DRw9uMqNaYgxx_5BTcPsjbU',
    appId: '1:963645798761:web:1682c7a3fa724aba3e25f8',
    messagingSenderId: '963645798761',
    projectId: 'cooperadora-app',
    authDomain: 'cooperadora-app.firebaseapp.com',
    storageBucket: 'cooperadora-app.firebasestorage.app',
  );
}
